created autocomment-pr-merge.yml
pooranjoyb/popShop pull request #123
Opened 2024-05-20 22:50 UTC by Asymtode712

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Fixes #120 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# Screenshort

![PR merged](https://github.com/pooranjoyb/popShop/assets/115717746/7376f961-0671-4b69-a5a0-ac589f5534a8)

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-20 22:50 UTC, pooranjoyb reviewed
Great job, @Asymtode712! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-05-20 22:51 UTC, Asymtode712 commented
@pooranjoyb please review my PR and merge it if it is good to go

2024-05-21 14:43 UTC, pooranjoyb requested changes

2024-05-21 14:43 UTC, pooranjoyb commented on .github/workflows/autocomment-pr-merge.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
change this to `USER_TOKEN`

2024-05-21 14:43 UTC, pooranjoyb commented on .github/workflows/autocomment-pr-merge.yml
> +          -H "Authorization: Bearer $GITHUB_TOKEN" \
change this to `USER_TOKEN`

2024-05-21 14:50 UTC, Asymtode712 commented on .github/workflows/autocomment-pr-merge.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
ok

2024-05-21 14:50 UTC, Asymtode712 commented on .github/workflows/autocomment-pr-merge.yml
> +          -H "Authorization: Bearer $GITHUB_TOKEN" \
ok

2024-05-21 14:52 UTC, Asymtode712 commented
@pooranjoyb done with the changes as requested by you

2024-05-22 17:35 UTC, pooranjoyb commented
Bruh the key should remain the same as  `GITHUB_TOKEN` 
I said only the values to `USER_TOKEN`
@Asymtode712

2024-05-22 17:41 UTC, Asymtode712 commented
@pooranjoyb you have assign your PAT to USER_TOKEN right?

2024-05-22 17:41 UTC, Asymtode712 commented
@pooranjoyb If yes then it wouldn't affect the code

2024-05-22 17:42 UTC, pooranjoyb commented
Its already set. Just make it `GITHUB_TOKEN : USER_TOKEN` 
@Asymtode712

2024-05-22 17:46 UTC, Asymtode712 commented
@pooranjoyb ok as you say but it won't make any difference as the key is just a mere variable so it can be named anything the thing whcih matters is the value

2024-05-22 17:48 UTC, Asymtode712 commented
@pooranjoyb done the changes, please review and merge it

2024-05-22 17:51 UTC, merged

2024-05-22 17:51 UTC, pooranjoyb commented
Nice work @Asymtode712 :rocket: