Added hover effect in shop and product page
pooranjoyb/popShop pull request #145
Opened 2024-05-26 10:29 UTC by Mujtabaa07

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #69 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-26 10:29 UTC, pooranjoyb reviewed
Great job, @Mujtabaa07! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-05-27 13:15 UTC, pooranjoyb commented
Hey @Mahitej28 could you please review this?

2024-05-27 13:15 UTC, Mahitej28 commented
> Hey @Mahitej28 could you please review this?

Sure

2024-05-27 13:54 UTC, Mahitej28 commented
@Mujtabaa07 there are some changes made in the main branch I suggest you take a pull from `dev` so that I can preview it.

2024-05-27 13:56 UTC, Mujtabaa07 commented
Sure

2024-05-27 14:15 UTC, Mahitej28 requested changes
Do the requested changes

2024-05-27 14:15 UTC, Mahitej28 commented on src/pages/Home/ProductStyles.css
> +img {
@Mujtabaa07 why have you created a separate CSS file for the animation, add your elements in `index.css` with proper comments.

2024-05-27 14:18 UTC, Mujtabaa07 commented on src/pages/Home/ProductStyles.css
> +img {
Sure I'll make changes now

2024-05-27 14:40 UTC, Mujtabaa07 commented on src/pages/Home/ProductStyles.css
> +img {
@Mahitej28 , I have made the requested changes. Please review.

2024-05-28 10:03 UTC, Mahitej28 approved these changes

2024-05-28 10:04 UTC, Mahitej28 commented
Looks good to me will merge by end of the day!

2024-05-28 10:05 UTC, merged