Feature/update signup process
pooranjoyb/popShop pull request #159
Opened 2024-05-30 16:08 UTC by me-shweta

In **utils/schema.ts**, I updated the SignUpSchema to include additional fields like FirstName, LastName, Gender, Phone, Address, and Account Creation Date. In **auth.ts**, I integrated the updated schema to validate user signup data in the authentication component.

Fixes #148 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# Checklist:
give a X on it which is applicable

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-30 16:08 UTC, pooranjoyb reviewed
Great job, @me-shweta! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-05-30 17:18 UTC, pooranjoyb commented
There are build errors. Fix them and commit. Run `npm run build` to detect the errors in the code. 

![image](https://github.com/pooranjoyb/popShop/assets/90945182/960d317d-5ad8-44bc-bece-9fbf3f3fc14d)

@me-shweta

2024-05-31 05:19 UTC, pooranjoyb requested changes

2024-05-31 05:19 UTC, pooranjoyb commented on src/pages/Auth/Auth.tsx
Hii @me-shweta I don't see much changes that you did here. 
Also `interface USER` is not updated.

2024-05-31 05:19 UTC, pooranjoyb commented on src/utils/schema.ts
`schema` definition is not proper. :/

2024-05-31 08:49 UTC, me-shweta commented
@pooranjoyb Tell me, is there any problem still? And I'm just reminding, if everything is fine, don't forget to add labels to this pull request.

2024-05-31 16:50 UTC, pooranjoyb requested changes

2024-05-31 16:50 UTC, pooranjoyb commented on package.json
I didn't understand why did you added `jest` for testing.

2024-05-31 16:50 UTC, pooranjoyb commented on src/components/Button.tsx
I guess refactoring `Button.jsx` wasn't a part of the issue.

2024-05-31 16:50 UTC, pooranjoyb commented on src/utils/schema.ts
> -    .min(3, "Username must be at least 3 characters")
Doesn't need a `message` key.

2024-05-31 16:50 UTC, pooranjoyb commented on vite.config.ts
Revert this. Unnecessary changes.

2024-05-31 17:23 UTC, pooranjoyb commented
Please read `CONTRIBUTING GUIDELINES` seems like you didn't run `npm run watch-css` for tailwind. This eventually broke the UI :/ @me-shweta 

![image](https://github.com/pooranjoyb/popShop/assets/90945182/08e54403-d66d-4005-8faa-970df0f5fe23)

2024-05-31 18:21 UTC, me-shweta commented
@pooranjoyb I have changed the code of the files, let me know if the problem still persists. :_)

2024-06-01 05:10 UTC, pooranjoyb commented
Seems like there are lotta issues here, even the Ui is not fixed. So, looking at your efforts to fix it, I'm merging it to `test` branch :/ But sorry to say that can't merge into `dev`

You'll still get the `gssoc` label but can't assign `level-2` to this :/ @me-shweta

2024-06-01 05:20 UTC, merged

2024-06-01 08:06 UTC, me-shweta commented
@pooranjoyb Sorry, I couldn't manage to do it in time. I think I should stay away from coding issues. By the way, thank you very much for your support. :/

2024-06-01 10:16 UTC, pooranjoyb commented
> @pooranjoyb Sorry, I couldn't manage to do it in time. I think I should stay away from coding issues. By the way, thank you very much for your support. :/
> By the way, these PR points will be considered, right? Or do I need to be assigned as the PR's assignee as well?

Yes it will be considered as a valid contribution, don't worry. And yes, I'd say try with easier UI issues. Don't just give up with bugs/problems easily. Try to understand how things actually work, use chatgpt to understand codebase. This will really help you understand better. @me-shweta