fixed to allow uesr to explore without login
pooranjoyb/popShop pull request #195
Opened 2024-06-05 09:50 UTC by Utsavladia

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #169 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**
Tested by going to all the routes.

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

give screenshorts and vedio of the changes you made

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-05 09:50 UTC, pooranjoyb reviewed
Great job, @Utsavladia! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-06-05 14:24 UTC, pooranjoyb commented
Fix the build errors. Verify with `npm run build` @Utsavladia 
 
![image](https://github.com/pooranjoyb/popShop/assets/90945182/9820fbef-926d-4343-83e0-d29f68208d8e)

2024-06-05 19:01 UTC, pooranjoyb commented
There are conflicts. Fix them. And lmk when are you free tomorrow, there are lot of issues that needs to be covered. @Utsavladia

2024-06-06 04:09 UTC, Utsavladia commented
@pooranjoyb I have resolved the conflicts.
And I am free till 2pm.

2024-06-06 04:24 UTC, pooranjoyb commented
Okay try to fix this now. @Utsavladia 

![image](https://github.com/pooranjoyb/popShop/assets/90945182/af2ce580-35cf-4db6-a483-b9dbc472a765)

2024-06-06 07:27 UTC, Mahitej28 commented
> Okay try to fix this now. @Utsavladia
> 
> ![image](https://private-user-images.githubusercontent.com/90945182/337099630-af2ce580-35cf-4db6-a483-b9dbc472a765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTkxMDYsIm5iZiI6MTcxNzY1ODgwNiwicGF0aCI6Ii85MDk0NTE4Mi8zMzcwOTk2MzAtYWYyY2U1ODAtMzVjZi00ZGI2LWE0ODMtYjlkYmM0NzJhNzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA3MjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NDEyMjMyMGI4NTAxODNmMDI5NWM2Y2Y0ZDEwOTZmMGVlNTQyMGFhMDc5OWZmMmQ5ZjZlNjlmZmE4MDViMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNLExRtdC5_6pHESAI2VjVcvTj7oZBpixGB7MyX7_lc)

@Utsavladia try to work upon this, also there are merge conflicts take a pull from `dev` and then start working

2024-06-06 09:13 UTC, Utsavladia commented
@Mahitej28 @pooranjoyb 
Fixed the Nav links in updated floating navbar and undefined section of dropdown.
![image](https://github.com/pooranjoyb/popShop/assets/124615886/2a5ad1a4-c046-41a0-b89e-ff5f345b7e6c)

2024-06-06 19:09 UTC, pooranjoyb commented
Bruh, please remove use Conditional rendering for Login and Logout. Obviously how will a user Logout without Login?
@Utsavladia

2024-06-06 19:11 UTC, pooranjoyb requested changes

2024-06-06 19:11 UTC, pooranjoyb commented on src/components/Navbar.tsx
> +                    {userName ? `${userName}` : <p>Login</p>}
change this :/

```js
{username ? `${username}` : <p> Profile </p>}

```

2024-06-08 03:23 UTC, pooranjoyb commented
Fix the conflicts. @Utsavladia

2024-06-08 06:42 UTC, Mahitej28 commented
@Utsavladia your pr has merge conflicts, resolve that and take a pull from `dev` before pushing commits.

2024-06-09 13:34 UTC, pooranjoyb commented
Hii @Utsavladia please check the build errors. run `npm run build` in your local machine and debug accordingly. :)

2024-06-09 15:30 UTC, Utsavladia commented
@pooranjoyb 
sure,
Resolved the conflicts and debugged the build error.

2024-06-11 08:44 UTC, Mahitej28 commented
@Utsavladia I can still see merge conflicts resolve it first

2024-06-11 17:20 UTC, Utsavladia commented
@Mahitej28 
I hope it is fixed now.

2024-06-11 19:13 UTC, pooranjoyb commented
merge conflicts :/ @Utsavladia

2024-06-13 13:24 UTC, pooranjoyb commented
Closing as inactive.

2024-06-13 13:28 UTC, Utsavladia commented
@pooranjoyb 
Sir, 
I kept resolving the conflicts again and again but due to delay in merging the branch new conflicts used to come and now also I could have resolved it I dont know how this notification got mixed.
sir I have spent time on this issue I request you to kindly let me fix and make it a successfull merge.

2024-06-13 13:51 UTC, pooranjoyb commented
Okay @Mahitej28 & @AjayAsnani will check and respond accordingly.

2024-06-17 11:00 UTC, Mahitej28 commented
@Utsavladia will give you two days time to complete it.

2024-06-17 13:14 UTC, Utsavladia commented
@pooranjoyb @Mahitej28 
Resolved the conflicts and synced with the latest branch I hope now it is working perfectly fine..

2024-06-17 15:31 UTC, merged

2024-06-17 16:38 UTC, Utsavladia commented
@Mahitej28 
Mam this merge did not get counted in my contributions to GSSoC.
I think you will also have to assign this merge to me so that it gets counted 😊

2024-06-18 04:43 UTC, pooranjoyb commented
> @Mahitej28 Mam this merge did not get counted in my contributions to GSSoC. I think you will also have to assign this pulll request to me so that it gets counted 😊

Wait for 24 hours, it takes time to update.