Terms and conditions UI refactor.
pooranjoyb/popShop pull request #199
Opened 2024-06-05 18:14 UTC by yashi-15

Refactoring Terms & Conditions UI.

Fixes #188 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# Screenshorts and Vedios:
![Screenshot (579)](https://github.com/pooranjoyb/popShop/assets/132138302/b6ddd3e0-0488-4d00-a449-cf1d4a8e9cd0)
![Screenshot (580)](https://github.com/pooranjoyb/popShop/assets/132138302/8dd5bfcf-70e4-4335-aa90-6caf64f2a36b)
![Screenshot (581)](https://github.com/pooranjoyb/popShop/assets/132138302/f9ed3e5d-545c-4693-b02b-7edb5c3ac68c)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-05 18:15 UTC, pooranjoyb reviewed
Great job, @yashi-15! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-06-06 07:11 UTC, Mahitej28 commented
@yashi-15 you need to look at the responsiveness of the website its getting distorted.
![image](https://github.com/pooranjoyb/popShop/assets/98276915/2e512b14-d4a4-43d8-9adf-f8645f8608ed)


Also the images are not loading.

2024-06-06 07:14 UTC, Mahitej28 commented on src/pages/T&C/TermsCond.tsx
> +                <div className="flex gap-4 items-center">
Add proper classnames

2024-06-06 11:40 UTC, yashi-15 commented on src/pages/T&C/TermsCond.tsx
> +                <div className="flex gap-4 items-center">
Do you mean to add className defining each block? so that it's easy to identify each block from the code. Or something else...?

2024-06-06 11:44 UTC, yashi-15 commented
Hi @Mahitej28, I checked this thing in my browser. There is no issue with the responsiveness or the images. Can you tell me for which specific screen size it's not responsive because in my browser its working good for every screen size...

![Screenshot (582)](https://github.com/pooranjoyb/popShop/assets/132138302/2430b687-d9f8-4bf6-a77e-ad4699dc7d8f)
![Screenshot (584)](https://github.com/pooranjoyb/popShop/assets/132138302/7b3e4ebf-68fd-4838-8b7a-70ab207369de)
![Screenshot (585)](https://github.com/pooranjoyb/popShop/assets/132138302/0ff558ca-de4f-41a7-8c08-8ea2a1c9d1d0)
![Screenshot (586)](https://github.com/pooranjoyb/popShop/assets/132138302/a1718389-f5ba-4848-954f-7bb93f4a9251)
![Screenshot (588)](https://github.com/pooranjoyb/popShop/assets/132138302/a148bee6-457a-4cc4-838b-424463183180)

2024-06-06 16:08 UTC, AjayAsnani commented
Work on responsiveness properly there are a lot of errors and complete it by tomorrow noon. @yashi-15

2024-06-06 16:13 UTC, AjayAsnani reviewed
Work on responsiveness properly there are a lot of errors and complete it by tomorrow noon. @yashi-15

2024-06-06 19:03 UTC, pooranjoyb commented
Hii @yashi-15 I can see the issue in Mozila too!
Check the deployment.

![image](https://github.com/pooranjoyb/popShop/assets/90945182/f80dcccb-9203-4d5c-800d-a220d701dcd0)

2024-06-06 19:06 UTC, pooranjoyb requested changes

2024-06-06 19:06 UTC, pooranjoyb commented on src/pages/T&C/TermsCond.tsx
> +                <div className="flex gap-4 items-center">
She meant that what's the use of 3 empty divs here and check the responsiveness. Please make sure you run `npm run watch-css` while development. Please check the `CONTRIBUTING GUIDELINES`

![image](https://github.com/pooranjoyb/popShop/assets/90945182/5842b91a-8471-4520-873e-18e795b9916c)

2024-06-07 07:42 UTC, Mahitej28 commented
> Hii @yashi-15 I can see the issue in Mozila too! Check the deployment.
> 
> ![image](https://private-user-images.githubusercontent.com/90945182/337403184-f80dcccb-9203-4d5c-800d-a220d701dcd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDU5ODcsIm5iZiI6MTcxNzc0NTY4NywicGF0aCI6Ii85MDk0NTE4Mi8zMzc0MDMxODQtZjgwZGNjY2ItOTIwMy00ZDVjLTgwMGQtYTIyMGQ3MDFkY2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3MzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MzhjMTY0YTgzMWUxZDVmODdhNzRmMGI4YjNiNDhhNjNjYmYzOTU2YTk1MDA5OTQzMWZmZGI3OWI0NzBkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WMyAfPshVmprCvoPwHfKiZixCDoUqT06Uv5mWA-XMJc)


Exactly even in chrome too, go through the deployment @yashi-15

2024-06-07 08:04 UTC, yashi-15 commented
> > Hii @yashi-15 I can see the issue in Mozila too! Check the deployment.
> > ![image](https://private-user-images.githubusercontent.com/90945182/337403184-f80dcccb-9203-4d5c-800d-a220d701dcd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDU5ODcsIm5iZiI6MTcxNzc0NTY4NywicGF0aCI6Ii85MDk0NTE4Mi8zMzc0MDMxODQtZjgwZGNjY2ItOTIwMy00ZDVjLTgwMGQtYTIyMGQ3MDFkY2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3MzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MzhjMTY0YTgzMWUxZDVmODdhNzRmMGI4YjNiNDhhNjNjYmYzOTU2YTk1MDA5OTQzMWZmZGI3OWI0NzBkYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WMyAfPshVmprCvoPwHfKiZixCDoUqT06Uv5mWA-XMJc)
> 
> Exactly even in chrome too, go through the deployment @yashi-15

@Mahitej28 Yes, I checked now... I was not checking the deployed one earlier. I will solve this issue asap.

2024-06-08 05:46 UTC, yashi-15 commented
Hey @pooranjoyb @Mahitej28 @AjayAsnani , I have solved the problem. Please review it and inform me if any further modifications are required.

2024-06-08 06:02 UTC, pooranjoyb approved these changes

2024-06-08 06:45 UTC, Mahitej28 commented
Looks go to me, will merge it !

2024-06-08 06:54 UTC, Mahitej28 approved these changes

2024-06-08 06:59 UTC, merged