fix: ui container responsiveness
pooranjoyb/popShop pull request #211
Opened 2024-06-08 08:55 UTC by harini-1597

Fixes # [(200)](https://github.com/pooranjoyb/popShop/issues/200#issuecomment-2154321586)

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

## How Has This Been Tested?

Run code locally on machine, use developer tools in Chrome under "Inspect" to check responsiveness on different screens.

## Screenshots and Videos:

https://github.com/pooranjoyb/popShop/assets/128628820/9e236f38-f12c-437e-90f5-2a848f77c4d0

# Checklist:
give a X on it which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-08 08:55 UTC, pooranjoyb reviewed
Great job, @harini-1597! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-06-11 08:21 UTC, harini-1597 commented
you can merge the pr

2024-06-11 09:29 UTC, Mahitej28 commented on src/pages/Home/Home.tsx
> +        className="max-w-screen-xl flex flex-col lg:flex-row justify-between items-center pb-12 pt-24 sm:pt-64 lg:pt-12 w-full"
Add `overflow-hidden` value because its leading to a horizontal scroll-bar and that is not needed.

2024-06-11 09:30 UTC, Mahitej28 requested changes
@harini-1597 look upon the changes mentioned also @pooranjoyb has told you to fix the `<head />`

2024-06-11 12:18 UTC, harini-1597 commented
Hey; if you use overflow-hidden the element heading gets cutoff, which was the main UI fix that was to be implemented. And I tried, but I'm unable to really fix that and make the x-scrollbar dissappear.

2024-06-11 17:37 UTC, pooranjoyb commented
> Hey; if you use overflow-hidden the element heading gets cutoff, which was the main UI fix that was to be implemented. And I tried, but I'm unable to really fix that and make the x-scrollbar dissappear.

okay np. lemme check with this once.

2024-06-11 17:38 UTC, merged