feat: Subscribe component added
pooranjoyb/popShop pull request #230
Opened 2024-06-12 12:02 UTC by RamakrushnaBiswal

Subscribe component added

Fixes #217 solved

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshorts and Vedios:

![image](https://github.com/pooranjoyb/popShop/assets/125277258/1f3bc7a4-2dad-4140-ab6e-add3c5ece59d)
![image](https://github.com/pooranjoyb/popShop/assets/125277258/b27c1d70-8e11-4cd8-8eb4-4478c283df81)
small screen

# Checklist:
give a X on it which is applicable

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-12 12:02 UTC, pooranjoyb reviewed
Great job, @RamakrushnaBiswal! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-06-12 14:02 UTC, RamakrushnaBiswal commented
@Mahitej28 @pooranjoyb review the PR

2024-06-12 16:40 UTC, pooranjoyb requested changes

2024-06-12 16:40 UTC, pooranjoyb commented on src/pages/Home/Home.tsx
> +      <Subscribe />
No need to create a separate component for Subscribe. Add this component inside Footer. So that we have it everywhere wherever there's Footer.

2024-06-12 16:49 UTC, RamakrushnaBiswal commented on src/pages/Home/Home.tsx
> +      <Subscribe />
okey

2024-06-13 06:30 UTC, pooranjoyb approved these changes

2024-06-13 06:31 UTC, merged

2024-06-13 06:31 UTC, pooranjoyb commented
Nice work @RamakrushnaBiswal 🚀