minor ui + utility bugs fixes
pooranjoyb/popShop pull request #250
Opened 2024-06-17 12:26 UTC by SandipGyawali

- skeleton-loader added	in Our Store
- cart model updated with real-data with image,	price and name
- table	header and cupon removal for empty cart
- footer contact-us refactor used in the header-nav section

Fixes #236

2024-06-17 12:27 UTC, pooranjoyb reviewed
Great job, @SandipGyawali! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-06-17 14:30 UTC, pooranjoyb commented
Deployment has failed, please check by running `npm run build` and debug accordingly @SandipGyawali

2024-06-17 15:38 UTC, SandipGyawali commented
> Deployment has failed, please check by running `npm run build` and debug accordingly @SandipGyawali

@pooranjoyb i guess it's fixed

2024-06-20 14:23 UTC, Mahitej28 commented
@SandipGyawali your branch has merge conflicts in `Navbar.tsx` and Shop.tsx` kindly resolve, otherwise it can't be merged

2024-06-20 14:29 UTC, Mahitej28 commented on src/components/Skeleton/Content.tsx
> +function SkeletonWithContent() {
@pooranjoyb is there a need to create a separate Skeleton folder?, rest all looks good to me.

2024-06-20 14:31 UTC, Mahitej28 reviewed
@pooranjoyb have a look at it.

2024-06-20 14:58 UTC, pooranjoyb requested changes

2024-06-20 14:58 UTC, pooranjoyb commented on src/components/Skeleton/Content.tsx
> +function SkeletonWithContent() {
Nope not needed, we can directly import and use skeletion wherever necessary. Please check @SandipGyawali

2024-06-20 14:58 UTC, pooranjoyb commented
Also resolve the conflicts @SandipGyawali

2024-06-24 07:29 UTC, Mahitej28 approved these changes

2024-06-25 13:00 UTC, pooranjoyb approved these changes

2024-06-25 13:01 UTC, merged