Added Google OAuth
pooranjoyb/popShop pull request #271
Opened 2024-06-24 12:54 UTC by masterboy376

Added Google OAuth using google cloud and Supabase.
Admin is advised to configure Google OAuth on google cloud and Supabase after merging this PR.

Fixes #265

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# Screenshots and Videos:

[screen-recorder-mon-jun-24-2024-18-18-33.webm](https://github.com/pooranjoyb/popShop/assets/92575005/a86bfbf4-cb68-4dfc-ab7c-3e26b4cb7d38)

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-24 12:54 UTC, pooranjoyb reviewed
Great job, @masterboy376! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-06-24 12:57 UTC, masterboy376 commented
@pooranjoyb PTAL

2024-06-25 08:23 UTC, pooranjoyb commented
> @pooranjoyb PTAL

show me the profile. how is the user created in `supabase`??? @masterboy376

2024-06-25 12:32 UTC, masterboy376 commented
@pooranjoyb, here is the screenshot
![Screenshot (172)](https://github.com/pooranjoyb/popShop/assets/92575005/f7109686-fec4-44c5-87ba-1c821efc1bf3)

2024-06-25 12:40 UTC, pooranjoyb commented
yeah so you can see that we need to add something like `not-found`
Also are we saving this entire thing to Users table in supabase?

2024-06-25 12:43 UTC, pooranjoyb requested changes

2024-06-25 12:43 UTC, pooranjoyb commented on src/pages/Auth/Oauth.tsx
> +            gender: "",
update this

2024-06-26 01:39 UTC, masterboy376 commented on src/pages/Auth/Oauth.tsx
> +            gender: "",
done

2024-06-26 01:39 UTC, masterboy376 commented
@pooranjoyb PTAL 
![Screenshot (173)](https://github.com/pooranjoyb/popShop/assets/92575005/b3beb799-c2a7-4114-ac7a-2b30dffc2492)

2024-06-27 05:46 UTC, masterboy376 commented
@pooranjoyb PTAL

2024-06-27 17:00 UTC, pooranjoyb commented
> @pooranjoyb PTAL

Not working. Please check, something might be wrong :/

2024-06-28 02:23 UTC, masterboy376 commented
Hello @pooranjoyb 
This was happening due to domain mismatch in supabase redirect urls. Fixed it. Now login is working on both vercel deployments as well as local servers.
[screen-recorder-fri-jun-28-2024-07-50-58.webm](https://github.com/pooranjoyb/popShop/assets/92575005/176f3c0c-b073-4b68-8373-0ed19a5e2223)

2024-06-28 02:31 UTC, masterboy376 commented
@pooranjoyb  PTAL

2024-06-28 12:38 UTC, pooranjoyb commented
> @pooranjoyb  PTAL

OK will review and update accordingly.

2024-06-28 13:10 UTC, pooranjoyb commented
Hey @masterboy376 Do let me the environment variables I need to add for this feature. Otherwise everything looks good for the merge.

2024-06-28 13:12 UTC, masterboy376 commented
@pooranjoyb there is no additional env variable needs to be added

2024-06-28 13:14 UTC, masterboy376 commented
@pooranjoyb However I have created the Oauth consent screen using my personal google  cloud account. So, when ever you have time, do create a consent screen using organization's account.

2024-06-28 13:15 UTC, pooranjoyb approved these changes

2024-06-28 13:17 UTC, pooranjoyb commented
> @pooranjoyb However I have created the Oauth consent screen using my personal google cloud account. So, when ever you have time, do create a consent screen using organization's account.

Yes, I do need to set this up. Drop me the steps below.

2024-06-28 13:19 UTC, merged