fixes issue #306 & #302
pooranjoyb/popShop pull request #314
Opened 2024-07-07 19:02 UTC by Tanishashrivas

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
#302  & #306 

## Type of change

Please give a X on it which is applicable

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**_Test A Describe here_**

**_Test B Describe here (if Requred)_**

# Screenshots and Videos:

Give screenshots and video of the changes you made

# Checklist:
Give a X on, which is applicable

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-07 19:03 UTC, pooranjoyb reviewed
Great job, @Tanishashrivas! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-07-08 04:39 UTC, pooranjoyb commented
Try running `npm run build` in the local to detect the build errors. @Tanishashrivas

2024-07-08 06:05 UTC, Tanishashrivas commented
> Try running `npm run build` in the local to detect the build errors. @Tanishashrivas

Done. Please review and merge.

2024-07-09 03:29 UTC, Tanishashrivas commented
@pooranjoyb sir? I'm hoping u would merge this today so i can start  working on other issue as well

2024-07-09 07:40 UTC, pooranjoyb requested changes

2024-07-09 07:40 UTC, pooranjoyb commented on src/pages/Shop/ProductDetail.tsx
> +            navigate('/home/shop/cart');
Navigating the User to the cart is not needed. Else everything looks good.

2024-07-09 08:15 UTC, Tanishashrivas commented
Done!

2024-07-10 16:57 UTC, pooranjoyb approved these changes

2024-07-10 16:57 UTC, merged

2024-07-10 16:57 UTC, pooranjoyb commented
Nice work @Tanishashrivas