product card as well as img
pooranjoyb/popShop pull request #371
Opened 2024-07-27 07:24 UTC by Varsani2520

i solve the card size issue as well as imagesnot displaying issue 

Fixes # (issue)
#369 

## Type of change

Please give a X on it which is applicable

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor Code
- [ ] A documentation update
- [ ] Others(mentioned in the issue number)

# Screenshots and Videos:

![image](https://github.com/user-attachments/assets/966cd822-0ebc-4a6b-a453-d188b79737e5)

# Checklist:
Give a X on, which is applicable

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-07-27 07:24 UTC, pooranjoyb reviewed
Great job, @Varsani2520! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-07-27 07:25 UTC, Varsani2520 commented
i added img in supabase and remove dummy images as well as solve the size 

@pooranjoyb review it

2024-07-27 13:25 UTC, pooranjoyb requested changes

2024-07-27 13:25 UTC, pooranjoyb commented on src/pages/Shop/Shop.tsx
> +      console.log("daata",data)// Initially display all products
remove this console-log

2024-07-27 13:27 UTC, Varsani2520 commented on src/pages/Shop/Shop.tsx
> +      console.log("daata",data)// Initially display all products
Ok

2024-07-27 13:33 UTC, Varsani2520 commented
@pooranjoyb now check it

2024-07-27 13:57 UTC, pooranjoyb commented
Also do #373 and #374 in this same PR only. @Varsani2520

2024-07-27 14:15 UTC, Varsani2520 commented
@pooranjoyb ,first this PR merged so i can work on #373 and #374

2024-07-27 18:04 UTC, pooranjoyb commented
> @pooranjoyb ,first this PR merged so i can work on #373 and #374

yeh do those thanges in this same PR only.

2024-07-29 04:13 UTC, pooranjoyb requested changes

2024-07-29 04:13 UTC, pooranjoyb commented on src/pages/Profile/EditProfileModal.tsx
> +const phoneSchema = z.string().refine((value) => {
Hey @Varsani2520 we already have the schema for Phone number please check the Zod Validation for phone in utils

2024-07-29 04:14 UTC, Varsani2520 commented on src/pages/Profile/EditProfileModal.tsx
> +const phoneSchema = z.string().refine((value) => {
@pooranjoyb ,i added strict validation on phone schema user only allowed to 10 digit in mobile number

2024-07-29 04:15 UTC, Varsani2520 commented
@pooranjoyb ,i fixed #374 
![image](https://github.com/user-attachments/assets/ffd12d96-9d9a-4215-88a8-452d373f3673)

2024-07-29 04:19 UTC, pooranjoyb commented on src/pages/Profile/EditProfileModal.tsx
> +const phoneSchema = z.string().refine((value) => {
> @pooranjoyb ,i added strict validation on phone schema user only allowed to 10 digit in mobile number

Opps sorry, my bad :/ I thought u added manual validation.

2024-07-29 04:19 UTC, merged