footer navigation
pooranjoyb/popShop pull request #52
Opened 2024-05-12 22:34 UTC by Srishtiii19

![Screenshot (366)](https://github.com/pooranjoyb/popShop/assets/121797105/298569bb-fa48-46b9-ab2c-336d56350ad5)

2024-05-12 22:48 UTC, Srishtiii19 commented
i have made footer @pooranjoyb, if any changes required then please let me know i'll update it.

2024-05-13 04:18 UTC, pooranjoyb commented
Seems like a complete new design. Please don't change the overall design pattern. 
I guess you were only supposed to add the links and work on the navigation, right? @Srishtiii19

2024-05-13 05:36 UTC, Srishtiii19 commented
hello @pooranjoyb, there seem to be some confusion from my end, i'll change the bar. Also can you please mention icons you would want in the bar?

2024-05-13 05:46 UTC, pooranjoyb commented
> hello @pooranjoyb, there seem to be some confusion from my end, i'll change the bar. Also can you please mention icons you would want in the bar?

Yes, I mean, just do the routings, you don't need to change the Footer design or anything :)

2024-05-13 05:47 UTC, Srishtiii19 commented
![Screenshot (369)](https://github.com/pooranjoyb/popShop/assets/121797105/4ec471d9-37b0-4f38-84f0-8f1ef5e3940f)

2024-05-13 05:49 UTC, Srishtiii19 commented
ohhh, the footer is already is made, i have seen that, i just have to link add links to it for navigation, right?

2024-05-13 10:51 UTC, pooranjoyb commented
> ohhh, the footer is already is made, i have seen that, i just have to link add links to it for navigation, right?

Haanji :) 
Just the navagations using `Link` of `react-router-dom`
@Srishtiii19

2024-05-13 10:55 UTC, pooranjoyb commented on index.html
> +    <script src="https://cdn.tailwindcss.com"></script>
remove this, follow contribution guidelines, you need to run `npm run watch-css` to generate tailiwind-css.

2024-05-13 10:56 UTC, pooranjoyb requested changes
@Mahitej28 @Srishtiii19

2024-05-13 10:56 UTC, pooranjoyb commented on src/pages/Error.tsx
> +      <footer className="text-gray-600 body-font">
Remove this entire Footer, udpate the `Footer` Component

2024-05-13 11:30 UTC, Srishtiii19 commented on src/pages/Error.tsx
> +      <footer className="text-gray-600 body-font">
yes sir doing it, removed the section that i have added now updating navigation in the footer via links @pooranjoyb

2024-05-13 11:45 UTC, Srishtiii19 commented
hello, @pooranjoyb @Mahitej28 i have made changes, please check

2024-05-13 18:39 UTC, Mahitej28 requested changes
Dont change the links that cant be redirected.

2024-05-13 18:41 UTC, Mahitej28 commented
@Srishtiii19 do the changes and also i advice u take a pull again from master and dev branch

2024-05-13 19:40 UTC, Srishtiii19 commented
work done as said @Mahitej28

2024-05-14 15:10 UTC, Mahitej28 requested changes
Kindly review all the links again and do the requested changes @Srishtiii19

2024-05-14 15:10 UTC, Mahitej28 commented on src/components/Footer.tsx
> +                      to="/cart"
@Srishtiii19 the link should be "/home/cart" just double-check all the links where you are routing. Kindly review all the links again.

2024-05-14 15:26 UTC, Srishtiii19 commented on src/components/Footer.tsx
> +                      to="/cart"
sure, will do it.

2024-05-15 08:16 UTC, Mahitej28 commented
@Srishtiii19 updates?

2024-05-15 08:38 UTC, Srishtiii19 commented
> @Srishtiii19 updates?

Hello @Mahitej28
I am at college rn, will complete this work today itself.

2024-05-15 11:50 UTC, Srishtiii19 commented
![Screenshot (373)](https://github.com/pooranjoyb/popShop/assets/121797105/666fddfb-830b-42a7-a8f8-a3057f725aea)

2024-05-15 11:53 UTC, Srishtiii19 commented
i dont know why it is showing error, wasnt showing before. Working on it.

2024-05-15 11:59 UTC, pooranjoyb commented
> i dont know why it is showing error, wasnt showing before. Working on it.

Run `npm install react-icons`

2024-05-15 15:54 UTC, Srishtiii19 commented
![Screenshot (375)](https://github.com/pooranjoyb/popShop/assets/121797105/e8712d7d-3628-4d79-b027-4f65b39d469a)

Unable to open any other page, please help

2024-05-16 04:59 UTC, pooranjoyb commented
did you follow the `contributing guidelines`?
Cross check everything with it. @Srishtiii19

2024-05-16 20:34 UTC, pooranjoyb commented
> > did you follow the `contributing guidelines`? Cross check everything with it. @Srishtiii19
> 
> hello @pooranjoyb, still facing the same issue none of the pages are opening except the login page. This wasn't an issue before.

DM in discord.

2024-05-17 07:16 UTC, Mahitej28 commented
@Srishtiii19 any updates? if the issue is still not solved yet DM me on Discord.

2024-05-17 10:43 UTC, Mahitej28 commented
Completed

2024-05-17 10:43 UTC, closed without merging