Animation added for HomePage
pooranjoyb/popShop pull request #66
Opened 2024-05-13 19:29 UTC by dev04sa

@pooranjoyb as required Animations added to HomePage by using Framer-motion .
Issue https://github.com/pooranjoyb/popShop/issues/38 also Resolved .
Kindly Review The PR.

2024-05-14 14:32 UTC, Mahitej28 commented on src/pages/Home/Home.tsx
> -        <img className="w-2/3 sm:w-1/3 py-4 sm:p-0" src="./images/hero.png" alt="" />
@dev04sa kindly don't change the responsive of the website

2024-05-14 14:33 UTC, Mahitej28 requested changes
Don't Change the repsonsiveness of website like don't delete the sm and max-screen values.
@dev04sa

2024-05-14 15:00 UTC, Mahitej28 commented
@dev04sa why are this images coming small as compared to others kindly look into this.
![image](https://github.com/pooranjoyb/popShop/assets/98276915/3d26c719-4ee3-426b-89a3-920e31b1395d)

2024-05-14 17:03 UTC, dev04sa commented
@Mahitej28  , I will look into changes.

2024-05-17 07:02 UTC, Mahitej28 commented
Looks good to me!

2024-05-17 07:05 UTC, merged