feat: profile page
pooranjoyb/popShop pull request #83
Opened 2024-05-16 05:49 UTC by Sid-80

## Describe
Profile page

## Issue
resolves #77 

![image](https://github.com/pooranjoyb/popShop/assets/101277141/cfc96b0a-f38e-4bb1-9d01-c4529c2b26a3)

![image](https://github.com/pooranjoyb/popShop/assets/101277141/9161ec35-aeb6-446f-8378-13d05e2b9db2)

![image](https://github.com/pooranjoyb/popShop/assets/101277141/53f4f8bd-e5dd-4443-9717-3a732dc421e3)

2024-05-16 05:49 UTC, pooranjoyb reviewed
Great job, @Sid-80! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-05-16 05:54 UTC, Sid-80 commented
@pooranjoyb Please review it!

2024-05-16 10:28 UTC, pooranjoyb requested changes

2024-05-16 10:28 UTC, pooranjoyb commented on src/pages/Profile/Profile.tsx
> +                <FaUser width={20} />
remove this icon

2024-05-16 10:28 UTC, pooranjoyb commented on src/pages/Profile/Profile.tsx
> +                Profile
Profile text should use `<Head>`

2024-05-16 10:28 UTC, pooranjoyb commented on src/pages/Profile/Profile.tsx
> +                <Head nextLine={true} h1={username!} h2="First Name Last Name" />
remove this h2 and add the first anme and last name in the details below. 
Only username should be there with `Head`

2024-05-16 10:28 UTC, pooranjoyb commented on src/components/Head.tsx
> +        {(nextLine) ? <br /> : ""}
no need next line, use multiple `<Head>` when needed.

2024-05-16 10:28 UTC, pooranjoyb commented on src/pages/Profile/Profile.tsx
> +                    <div className="hidden sm:block border border-l-[1px]" />
this divider should be a but lighter, use `gray-400`

2024-05-16 10:28 UTC, pooranjoyb commented on src/pages/Profile/Profile.tsx
> +            <div className="divider divider-neutral text-lg font-semibold sm:text-3xl divider-start">
romove divider

2024-05-16 10:30 UTC, pooranjoyb requested changes

2024-05-16 10:30 UTC, pooranjoyb commented on src/pages/Profile/Profile.tsx
> +            <img className="absolute opacity-30 -z-20 w-full h-[220px] sm:h-[350px] top-[-98px]" src="/images/backbest.jpeg" alt="" />
remove this image, possibly add a `Linear-Gradient` with the theme of the PopShop. 
Check `tailwind.config.js`

2024-05-17 16:18 UTC, pooranjoyb approved these changes

2024-05-17 16:19 UTC, pooranjoyb commented
Nice work with the page @Sid-80 🚀

2024-05-17 16:19 UTC, merged