removed bug 'when authenticated we still can go to auth page '
pooranjoyb/popShop pull request #96
Opened 2024-05-18 02:52 UTC by NIveX2169

Please do check routes !!

2024-05-18 02:52 UTC, pooranjoyb reviewed
Great job, @NIveX2169! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-05-18 02:58 UTC, pooranjoyb commented
None of the other routes seems to be working! Please check @NIveX2169 👀

2024-05-19 08:02 UTC, Mahitej28 commented
@NIveX2169 updates?

2024-05-19 08:04 UTC, NIveX2169 commented
> @NIveX2169 updates?
> 

I'm still working on it I need your help give me your discord

2024-05-20 17:47 UTC, pooranjoyb requested changes

2024-05-20 17:47 UTC, pooranjoyb commented on src/browserRoutes/routes/Routes.tsx
> -        element: <Profile />
Seems like you forgot to add the `profile` route :/

2024-05-21 09:19 UTC, Mahitej28 commented
@pooranjoyb have a look to it, seems good to me.

2024-05-23 17:12 UTC, pooranjoyb commented
Awesome work @NIveX2169 🚀 
Sorry for the delay :/

2024-05-23 17:12 UTC, merged