New Navbar
pooranjoyb/popShop pull request #99
Opened 2024-05-18 12:42 UTC by Vedant5751

@pooranjoyb Made the requested changes
![image](https://github.com/pooranjoyb/popShop/assets/104258810/37174507-311e-4d6e-a7c3-a8e260c7c58f)
![image](https://github.com/pooranjoyb/popShop/assets/104258810/0f9faec0-b5f9-4d1a-b625-d34c46af66c3)

2024-05-18 12:42 UTC, pooranjoyb reviewed
Great job, @Vedant5751! 🎉 Thank you for submitting your pull request. Your contribution is valuable and we appreciate your efforts to improve our project.<p>We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/pooranjoyb/popShop/blob/dev/CONTRIBUTING.md)</p>

2024-05-19 11:53 UTC, pooranjoyb requested changes

2024-05-19 11:53 UTC, pooranjoyb commented on package.json
> +    "clsx": "^2.1.1",
State the use of `clsx`

2024-05-19 11:53 UTC, pooranjoyb commented on src/components/Navbar2.tsx
There already exists a`Navbar` component right?
Why did you create another? @Vedant5751

2024-05-19 11:53 UTC, pooranjoyb commented on src/pages/Home/Home.tsx
This entire component is passed as a `Outlet` to the route itself. No need any `Component` here. Just add it to `Navbar` That'll do

2024-05-19 11:53 UTC, pooranjoyb commented on src/utils/cn.ts
What is this? Are you sure you watching the tailwind changes using `npm run watch-css`?

2024-05-19 11:54 UTC, pooranjoyb commented
Also add the `Glassmorphism` effect in the Navbar itself. Make it static. @Vedant5751

2024-05-19 12:31 UTC, Vedant5751 commented on package.json
> +    "clsx": "^2.1.1",
the navbar is made from aceternity ui,  hence the packages

2024-05-19 12:33 UTC, Vedant5751 commented on src/components/Navbar2.tsx
Created another because wanted to create a clean looking file since the previous navbar is made by someone else, so could hv conflicting class attributes. so to avoid such issues i created a new component.

2024-05-19 12:34 UTC, Vedant5751 commented on src/pages/Home/Home.tsx
same reason as above. if u still want the change then sure ill do it. but its just to avoid conflicts with the previous navbars classes. bcoz then it would mess up with the responsiveness as well.

2024-05-19 12:35 UTC, Vedant5751 commented on src/utils/cn.ts
its a util file required for aceternity ui, to import necessary dependencies.

2024-05-19 12:37 UTC, Vedant5751 commented
> Also add the `Glassmorphism` effect in the Navbar itself. Make it static. @Vedant5751

navbar is static now, also could u clarify if u want the entire previous existing navbar to hv the glassmorphism effect or not, since the navbar i created has the effect already.?(including popshopo.com and other)

2024-05-19 12:56 UTC, pooranjoyb commented
> > Also add the `Glassmorphism` effect in the Navbar itself. Make it static. @Vedant5751
> 
> navbar is static now, also could u clarify if u want the entire previous existing navbar to hv the glassmorphism effect or not, since the navbar i created has the effect already.?(including popshopo.com and other)

No need just the nav will do, Popshop is just for reference, we might replace it with logo later.

2024-05-19 13:54 UTC, Vedant5751 commented
@pooranjoyb what seems to be the issue? since i cant see the details of the error

2024-05-23 06:30 UTC, Mahitej28 commented
> @pooranjoyb what seems to be the issue? since i cant see the details of the error

Run `npm build` on the terminal you will get to know what are the build errors

2024-05-23 17:30 UTC, pooranjoyb commented
Hii @Vedant5751 Closing this as many changes are to be made and also there are many conflicts. 
Please pull latest changes from `dev` and raise a new PR, we'll review and merge accordingly :)

2024-05-23 17:30 UTC, closed without merging